<?php
/**
 * Back to Top Button
 *
 * @package      NWU2025
 * @author       Debbie Labedz
 * @since        1.0.0
 * @license      GPL-2.0+
 **/

/**
 * Enqueue back to top JavaScript
 */
function nwu_2025_back_to_top_scripts() {
	wp_enqueue_script(
		'nwu-back-to-top',
		get_theme_file_uri( '/assets/js/back-to-top.js' ),
		[],
		filemtime( get_theme_file_path( '/assets/js/back-to-top.js' ) ),
		true
	);
}
add_action( 'wp_enqueue_scripts', 'nwu_2025_back_to_top_scripts' );

/**
 * Add back to top button to footer
 */
function nwu_2025_back_to_top_button() {
	$icon = be_icon( [
		'icon' => 'chevron-up',
		'group' => 'utility',
		'size' => 24
	] );

	echo '<button class="back-to-top" aria-label="' . esc_attr__( 'Back to top', 'nwu-2025' ) . '">';
	echo '<span class="screen-reader-text">' . esc_html__( 'Back to top', 'nwu-2025' ) . '</span>';
	// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Icon is safely generated by be_icon()
	echo $icon;
	echo '</button>';
}
add_action( 'tha_footer_after', 'nwu_2025_back_to_top_button' );
